title: Darkwraith Covenant Blog
email: darkwraithcovenantpdx@gmail.com
author: Jose De Lara
logo: /assets/images/blog_images/shirtresized.png
tagline:  Ruminations about Music Technology, Programming, and Politics.
excerpt_separator: <!-- excerpt-end -->
description: Official website of the open source music and art project Darkwraith Covenant from Portland, OR.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.darkwraithcovenant.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter:
  username: darkwraithcoven
  card: summary
github_username:  darkwraithcovenant
plugins:
  - jekyll-seo-tag
facebook:
  app_id: 3298743140374937
